// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using aula_02_05.Data;

#nullable disable

namespace aula_02_05.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240509144400_Second")]
    partial class Second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("aula_02_05.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Classificacao_Do_Jogo");

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("Data_De_Postagem");

                    b.Property<int>("JogoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TxtAvaliation")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Conteudo_Da_Avaliacao");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("UserId");

                    b.ToTable("Tabela_Avaliacao");
                });

            modelBuilder.Entity("aula_02_05.Models.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvaliationId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DtComentario")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DtPostagem")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("Data_De_Postagem");

                    b.Property<string>("Jogo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("JogoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TxtAvaliation")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Texto_Do_Comentario");

                    b.Property<int?>("UseId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("useId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("AvaliationId");

                    b.HasIndex("JogoId");

                    b.HasIndex("UseId");

                    b.ToTable("Tabela_De_Comentario");
                });

            modelBuilder.Entity("aula_02_05.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Desenvolvedor_Do_Jogo");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Genero_Do_Jogo");

                    b.Property<DateTime>("Platform")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("Plataforma_Do_Jogo");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("Data_De_Publicacao");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Titulo_Do_Jogo");

                    b.HasKey("Id");

                    b.ToTable("Tabela_Jogo");
                });

            modelBuilder.Entity("aula_02_05.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateRegister")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("Data_Do_Registro");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Foto_De_Perfil");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("Usuario_Ativo");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Nick");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Hash_da_senha");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Email");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Nome_De_Usuario");

                    b.HasKey("Id");

                    b.ToTable("Tabela_usuario");
                });

            modelBuilder.Entity("aula_02_05.Models.Avaliacao", b =>
                {
                    b.HasOne("aula_02_05.Models.Jogo", "jogo")
                        .WithMany("Avaliations")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aula_02_05.Models.Usuario", "Usuario")
                        .WithMany("Avaliations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("jogo");
                });

            modelBuilder.Entity("aula_02_05.Models.Comentario", b =>
                {
                    b.HasOne("aula_02_05.Models.Avaliacao", "Avaliacao")
                        .WithMany()
                        .HasForeignKey("AvaliationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aula_02_05.Models.Jogo", null)
                        .WithMany("Comentario")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aula_02_05.Models.Usuario", "usuario")
                        .WithMany("Comentario")
                        .HasForeignKey("UseId");

                    b.Navigation("Avaliacao");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("aula_02_05.Models.Jogo", b =>
                {
                    b.Navigation("Avaliations");

                    b.Navigation("Comentario");
                });

            modelBuilder.Entity("aula_02_05.Models.Usuario", b =>
                {
                    b.Navigation("Avaliations");

                    b.Navigation("Comentario");
                });
#pragma warning restore 612, 618
        }
    }
}
